version: "3.7"

services:
  goserversaml:
    image: goserversaml:latest
    ports:
      - "8002:8002"
    networks:
      - public-net
  goserver:
    image: goserver:latest
    depends_on:
      - "goserversaml"
    ports:
      - "8001:8001"
    networks:
      - private-net
      - public-net
  osquery-ubuntu18:
    image: osquerydist:latest
    deploy:
      replicas: 2
    depends_on:
      - "goserver"
    networks:
      - private-net
networks:
  public-net:
  private-net:
